// src/components/Latex.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from "vue";

interface Props {
  latex?: string;
  block?: boolean;
  color?: string;
}

const { latex = "", block = false, color = "" } = defineProps<Props>();

const content = computed(() => latex);

const containerRef = ref<HTMLSpanElement>();

let isMounted = true;

const renderMath = async (): Promise<void> => {
  const el = containerRef.value;

  if (!el) return;

  if (!globalThis.MathJax?.typesetPromise) {
    setTimeout(() => {
      if (isMounted) void renderMath();
    }, 200);
    return;
  }

  const delimiter = block ? "$$" : "$";
  el.textContent = `${delimiter}${content.value}${delimiter}`;
  el.style.visibility = "hidden";

  try {
    await globalThis.MathJax.typesetPromise([el]);
    if (!isMounted) return;

    el.style.visibility = "visible";

    if (color) {
      const svg = el.querySelector("svg");
      if (svg) {
        svg.style.fill = color;
        svg.style.color = color;
        const paths = svg.querySelectorAll("path, rect, polygon");
        paths.forEach((path) => {
          (path as SVGElement).style.fill = color;
        });
      }
    }
  } catch {
    el.textContent = content.value;
    el.style.visibility = "visible";
  }
};

onMounted(() => {
  isMounted = true;

  watch(
    () => [color, latex],
    () => {
      void renderMath();
    },
  );

  void renderMath();
});

onBeforeUnmount(() => {
  isMounted = false;
});
</script>

<template>
  <span
    ref="containerRef"
    :style="{
      display: block ? 'block' : 'inline-block',
      color,
      verticalAlign: block ? undefined : 'middle',
      position: block ? undefined : 'relative',
      bottom: block ? undefined : '0.125em',
    }"
  />
</template>

// components/Latex.tsx
import type { FC } from "react";
import { memo, useEffect, useRef } from "react";

declare global {
  interface MathJaxStatic {
    typesetPromise?: (elements?: Element[]) => Promise<void>;
  }

  interface Window {
    MathJax?: MathJaxStatic;
  }
}

interface LatexProps {
  /** LaTeX string content (alternative to children) */
  latex?: string;
  /** LaTeX string content */
  children?: string;
  /** Whether to render as a block element ($$) */
  block?: boolean;
  /** Additional CSS classes */
  className?: string;
  /** Text color for the rendered LaTeX */
  color?: string;
}

/**
 * A unified LaTeX component that uses MathJax to render mathematical formulas.
 * Supports both inline and block modes, and custom coloring.
 */
export const Latex: FC<LatexProps> = memo(({ children, latex, block, className, color }) => {
  const containerRef = useRef<HTMLSpanElement>(null);
  const content = latex ?? children ?? "";

  useEffect(() => {
    let isMounted = true;
    const el = containerRef.current;

    if (!el) return;

    const renderMath = async (): Promise<void> => {
      // Wait for MathJax to load if it hasn't yet
      if (!window.MathJax?.typesetPromise) {
        setTimeout(() => {
          if (isMounted) void renderMath();
        }, 200);

        return;
      }

      // Set the content with appropriate delimiters for MathJax
      const delimiter = block ? "$$" : "$";

      el.textContent = `${delimiter}${content}${delimiter}`;
      el.style.visibility = "hidden"; // Hide until rendered to prevent flash

      try {
        await window.MathJax.typesetPromise([el]);

        if (isMounted) {
          el.style.visibility = "visible";

          // Apply color to SVG if provided
          if (color) {
            const svg = el.querySelector("svg");

            if (svg) {
              svg.style.fill = color;
              svg.style.color = color;

              // Override internal path fills to match the requested color
              const paths = svg.querySelectorAll("path, rect, polygon");

              paths.forEach((p) => {
                (p as SVGElement).style.fill = color;
              });
            }
          }
        }
      } catch (err) {
        console.warn("MathJax render error:", err);

        if (isMounted) {
          el.textContent = content; // Fallback to raw text
          el.style.visibility = "visible";
        }
      }
    };

    void renderMath();

    return (): void => {
      isMounted = false;
    };
  }, [content, block, color]);

  return (
    <span
      ref={containerRef}
      className={className}
      style={{
        display: block ? "block" : "inline-block",
        verticalAlign: block ? undefined : "middle",
        color,
        // Vertical alignment adjustment for inline math
        position: block ? undefined : "relative",
        bottom: block ? undefined : "0.125em",
      }}
    />
  );
});

Latex.displayName = "Latex";
